### ISSUE TITLE
SIMULACIÓN DE EXPRESIONES BOOLEANAS CON COMPUERTAS LÓGICAS EN EL PROTOBOARD

### ISSUE THREAD

**Issue by Eddi3mendoz** [SistemasTecTlaxiaco/compuertas-logicas-equipo-edwin#1]
[Practica Diseño de Circuitos Lógicos.pdf](https://github.com/user-attachments/files/18046146/Practica.Diseno.de.Circuitos.Logicos.pdf)
Vídeo Evidencia:
https://drive.google.com/file/d/1CXUwW6rqAe6Tzz6zo-uXj3pvbPVgE6v9/view?usp=sharing

**Comment by Ivan-PerezZ** [comment]
Portada:25/25
Procedimiento:25/25
Figuras, Ilustraciones y Fotografías:25/25
Resultados y conclusiones:25/25
Total:100/100

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
